# WARNING: This file is auto-generated by TestRunner._write_test_index()
# Do not edit manually. Changes will be overwritten on each test run.
# This file is necessary for test runner compatibility with exported binaries.

const SUITES := [
	"res://tests/autowrapper/test_exception_repro.gd",
	"res://tests/autowrapper/test_occt_basics.gd",
	"res://tests/autowrapper/test_occt_enums.gd",
]
