# WARNING: This file is auto-generated by TestRunner._write_test_index()
# Do not edit manually. Changes will be overwritten on each test run.
# This file is necessary for test runner compatibility with exported binaries.

const SUITES := [
	"res://tests/autowrapper/test_array_params.gd",
	"res://tests/autowrapper/test_collections.gd",
	"res://tests/autowrapper/test_default_params.gd",
	"res://tests/autowrapper/test_exception_repro.gd",
	"res://tests/autowrapper/test_fields.gd",
	"res://tests/autowrapper/test_leak_probe.gd",
	"res://tests/autowrapper/test_occt_basics.gd",
	"res://tests/autowrapper/test_occt_enums.gd",
	"res://tests/autowrapper/test_opaque_pointers.gd",
	"res://tests/autowrapper/test_standard.gd",
	"res://tests/autowrapper/test_std_types.gd",
	"res://tests/autowrapper/test_stream_callables.gd",
]
